"""One-time module setup: install deps and update AGENTS.md.

Run at container startup from entrypoint.sh.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path

from .module_loader import discover_modules, generate_modules_doc

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

AGENTS_MD = "/workspace/AGENTS.md"
BEGIN_MARKER = "<!-- MODULES:BEGIN -->"
END_MARKER = "<!-- MODULES:END -->"


def install_requirements(modules_dir: str) -> None:
    """Install requirements.txt for each module that has one."""
    for entry in sorted(Path(modules_dir).iterdir()):
        req = entry / "requirements.txt"
        if req.exists():
            log.info("Installing deps for module %s", entry.name)
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "--break-system-packages", "-q", "-r", str(req)],
                check=True,
            )


def update_agents_md(doc: str) -> None:
    """Replace content between MODULES markers in AGENTS.md."""
    if not os.path.exists(AGENTS_MD):
        log.warning("AGENTS.md not found at %s", AGENTS_MD)
        return

    with open(AGENTS_MD) as f:
        content = f.read()

    begin = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if begin == -1 or end == -1:
        log.warning("Module markers not found in AGENTS.md -- skipping update")
        return

    replacement = f"{BEGIN_MARKER}\n<!-- Auto-generated by module_setup.py -- do not edit manually -->\n\n{doc}\n{END_MARKER}"
    new_content = content[:begin] + replacement + content[end + len(END_MARKER):]

    with open(AGENTS_MD, "w") as f:
        f.write(new_content)

    log.info("Updated AGENTS.md with module documentation")


def main() -> None:
    modules_dir = "/workspace/.codex/modules"
    if not os.path.isdir(modules_dir):
        log.info("No modules directory found -- skipping module setup")
        return

    modules = discover_modules(modules_dir)
    log.info("Discovered %d module(s): %s", len(modules), [m.name for m in modules])

    install_requirements(modules_dir)

    doc = generate_modules_doc(modules)
    update_agents_md(doc)


if __name__ == "__main__":
    main()
